import bytenode from 'bytenode';
import fs from 'fs';
import path from 'path';
import { app } from 'electron';
import { fileURLToPath } from 'url';

// Define __dirname for ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// This script must be run via the 'electron' binary (not just node) 
// to ensure the V8 bytecode version matches the Electron runtime.

const distElectronPath = path.join(__dirname, '..', 'dist-electron');
const mainJsPath = path.join(distElectronPath, 'main.js');
const mainJscPath = path.join(distElectronPath, 'main.jsc');

console.log('🔒 Security: Compiling Main Process to Bytecode...');

if (fs.existsSync(mainJsPath)) {
  try {
    // 1. Compile the JS file generated by Vite into Bytecode
    bytenode.compileFile({
      filename: mainJsPath,
      output: mainJscPath
    });

    // 2. Overwrite main.js with a loader that requires the bytecode
    // This removes the readable source code from the final build.
    const loaderCode = `
      'use strict';
      require('bytenode');
      require('./main.jsc');
    `;

    fs.writeFileSync(mainJsPath, loaderCode);
    
    console.log('✅ Success: main.js converted to secure loader.');
    console.log(`   Bytecode generated at: ${mainJscPath}`);
    
  } catch (error) {
    console.error('❌ Error compiling bytecode:', error);
    if (app) app.quit();
    process.exit(1);
  }
} else {
  console.error('❌ Error: dist-electron/main.js not found. Run "vite build" first.');
  if (app) app.quit();
  process.exit(1);
}

// Exit the Electron process started to run this script
if (app) {
    app.quit();
}